version: "3.7"
services:
    haproxy:
        build:
            context: haproxy/
        ports:
            - 80:80
        volumes:
            - /Users/liorf/PycharmProjects/haproxy/haproxy/config:/config/
    elasticsearch:
        ports:
            - 9200:9200
            - 9300:9300
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        environment:
            - discovery.type=single-node
    kibana:
        ports:
            - 5601:5601
        image: docker.elastic.co/kibana/kibana:7.9.2
    logstash:
        image: docker.elastic.co/logstash/logstash:7.9.3
        volumes: 
            - /Users/liorf/PycharmProjects/haproxy/logstash/pipeline:/usr/share/logstash/pipeline/
    metricbeat:
        build:
            context: metricbeat/
    web:
        build:
            context: node/
    registrator:
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        image:
            gliderlabs/registrator:latest
        command: -internal=true consul://192.168.1.111:8500
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka1:
        build: kafka_new/
        ports:
            - "9192:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.1.111
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
            JMX_PORT: 1099
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock        
    # zookeeper:
    #     image: 'bitnami/zookeeper:latest'
    #     ports:
    #         - '2181:2181'
    #     environment:
    #         - ALLOW_ANONYMOUS_LOGIN=yes
    # kafka1:
    #     build:
    #         context: kafka/
    #     ports:
    #         - '9192:9092'
    #     environment:
    #         - KAFKA_BROKER_ID=1
    #         - KAFKA_LISTENERS=PLAINTEXT://:9092
    #         - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.111:9192
    #         - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    #         - ALLOW_PLAINTEXT_LISTENER=yes
    #         # - KAFKA_JMX_OPTS="-javaagent:/opt/bitnami/kafka/jolokia-jvm-1.6.2-agent.jar=port=8778,host=localhost -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.host=localhost -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Djava.net.preferIPv4Stack=true"
    #         # - KAFKA_OPTS="javaagent:/jolokia-jvm-1.6.2-agent.jar -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=9999  -Djava.security.auth.login.config=/var/private/sasl_acl/kafka.server.jaas.config"
    #     depends_on:
    #         - zookeeper
    # kafka2:
    #     image: 'bitnami/kafka:latest'
    #     ports:
    #         - '9292:9092'
    #     environment:
    #         - KAFKA_BROKER_ID=2
    #         - KAFKA_LISTENERS=PLAINTEXT://:9092
    #         - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.111:9292
    #         - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    #         - ALLOW_PLAINTEXT_LISTENER=yes
    #     depends_on:
    #         - zookeeper
    