version: "3.7"
services:
    haproxy:
        build:
            context: .
        ports:
            - 80:80
        volumes:
            - /Users/liorf/PycharmProjects/haproxy/config:/config/
    elasticsearch:
        ports:
            - 9200:9200
            - 9300:9300
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        environment:
            - discovery.type=single-node
    kibana:
        ports:
            - 5601:5601
        image: docker.elastic.co/kibana/kibana:7.9.2
        links:
            - elasticsearch:elasticsearch
    web:
        build:
            context: node/
    registrator:
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        image:
            gliderlabs/registrator:latest
        command: -internal=true consul://192.168.1.111:8500