version: "3.7"
services:
    haproxy:
        build:
            context: haproxy/
        ports:
            - 80:80
        volumes:
            - /Users/liorf/PycharmProjects/haproxy/haproxy/config:/config/
    elasticsearch:
        ports:
            - 9200:9200
            - 9300:9300
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        environment:
            - discovery.type=single-node
    kibana:
        ports:
            - 5601:5601
        image: docker.elastic.co/kibana/kibana:7.9.2
        links:
            - elasticsearch:elasticsearch
    logstash:
        image: docker.elastic.co/logstash/logstash:7.9.3
        volumes: 
            - /Users/liorf/PycharmProjects/haproxy/logstash/pipeline:/usr/share/logstash/pipeline/
    web:
        build:
            context: node/
    registrator:
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        image:
            gliderlabs/registrator:latest
        command: -internal=true consul://192.168.1.111:8500
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka1:
        image: 'bitnami/kafka:latest'
        ports:
            - '9192:9092'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.111:9192
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
    kafka2:
        image: 'bitnami/kafka:latest'
        ports:
            - '9292:9092'
        environment:
            - KAFKA_BROKER_ID=2
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.111:9292
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper            