version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    build: .
    ports:
      - "9192:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.111
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
